# Generated by Django 4.2.1 on 2023-07-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
